# Railway Configuration
# This file tells Railway how to build and start your Go application

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "go run main.go"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
